// models/Product.js

const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
    title:{
        type:String,
        requried:true,
        trim:true,
        min:3,
        max:50
    },
    description:{
        type:String,
        requried:true,
        trim:true,
        min:20,
        max:350
    },
    photo:{
        type:String,
    },
    photos:{
        type:String,
    },
    productCode:{
        type:String,
    },
    mainCategory:{
        type:String,
    },
    subCategory:{
        type:String,
    },
    unit:{
        type:String,
    },
    hasSecondaryUnit:{
        type:Boolean,
    },
    secondaryUnit:{
        type:String,
    },
    secondaryUnitRatio:{
        type:String,
    },
   
    initialStock:{
        type:String,
    },
    initialSecondaryStock:{
        type:String,
    },
    purchasePrice:{
        type:String,
    },
    sellPrice:{
        type:String,
    },
    sellPrice:{
        type:String,
    },
    purchasePriceSecondary:{
        type:String,
    },
    sellPriceSecondary:{
        type:String,
    },
    sellPriceSecondary:{
        type:String,
    },
    secondSellPrice:{
        type:String,
    },
    secondSellPriceSecondary:{
        type:String,
    },
    invoiceDescription:{
        type:String,
    },
    barcode:{
        type:String,
    },
    minExpireWarningDays:{
        type:String,
    },
    minStock:{
        type:String,
    },
    vatPercent:{
        type:String,
    },
    weight:{
        type:String,
    },
    length:{
        type:String,
    },
    width:{
        type:String,
    },
    height:{
        type:String,
    },
    moreInfo:{
        type:String,
    },
    
}, { timestamps: true });

module.exports = mongoose.model('Product', productSchema);
